### ISSUE TITLE
Creation of Docker image fails

### ISSUE THREAD

**Issue by stranljip** [grnet/agora-sp#17]
I try to start an instance with docker-compose as described in https://github.com/grnet/agora-sp/blob/master/README.md. I would expect that I can simply fire up the command there and get a working instance.

The creation of the Docker image however fails with
```
Status: Downloaded newer image for node:8
 ---> 8eeadf3757f4
Step 2/6 : RUN npm install --global yarn
 ---> Running in cf0310ded6c4
npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/yarn/bin/yarn.js
npm ERR! dest /usr/local/bin/yarn
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/yarn/bin/yarn.js' -> '/usr/local/bin/yarn'
npm ERR! File exists: /usr/local/bin/yarn
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-18T07_10_27_944Z-debug.log
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c npm install --global yarn' returned a non-zero code: 239
```

**Comment by kkoumantaros** [comment]
You are most probably using a newer version of NPM please use the requirements.txt to build your environment to run. If that does not work we will soon release a newer version.

**Comment by stranljip** [comment]
OK - it seems I will not be able to do that because as far as I understand it, I need Python 2. Since I am using a Mac and neither the current macOS nor Homebrew provide Python 2 anymore, I cannot meet the requirements. Thanks for answering though :-)

**Comment by kkoumantaros** [comment]
Yes we didn't migrate it yet yo Python 3 its our todo list but not top priority as it is not meant to be installed by 3rd parties yet
