### ISSUE TITLE
Unable to login using default accounts

### ISSUE THREAD

**Issue by MilosQL** [grnet/agora-sp#50]
Hi, I've followed the instructions for the Docker Compose setup (master branch, tag: v1.3.1) but unfortunately with not much success:

- I keep getting the "Login Error". None of the preconfigured accounts seem to work, although they are all present in DB.
- Docker container for backend takes some time to start but eventually ends up with "unhealthy" status.
- Frontend reports a number of  _'XYZ' is only available in ES6 (use 'esversion: 6')_ errors. 

Not sure if these problems are related. I have also tried with v1.3.0 but the result was more or less the same. Any suggestions on how to approach this? Thanks!

**Comment by themiszamani** [comment]
Could you please explain what you want to do?

**Comment by MilosQL** [comment]
I was trying to log in to the app using the preconfigured users.json accounts: 

    superadmin/12345
    provideradmin/12345
    service_admin_1/12345
    service_admin_2/12345
    observer/12345

but the login page keeps returning an error.  

At the moment, we just want to try and get ourselves familiar with the application in our lab/testing environment.

**Comment by kevangel79** [comment]
Hi @MilosQL did you followed the steps bellow ?
```
1. git clone git@github.com:grnet/agora-sp.git
2. docker-compose up -d
```
Make sure there is not another docker container or web app running on port 8000
After the `docker-compose up -d` command check with `docker-compose logs -f` the output of the docker containers.

A normal spin up of the containers should look like the following logs

```
agora-backend | Installed 14 object(s) from 1 fixture(s)
agora-backend | Installed 1 object(s) from 1 fixture(s)
agora-backend | Installed 5 object(s) from 1 fixture(s)
agora-backend | Installed 1 object(s) from 1 fixture(s)
agora-backend | Installed 1 object(s) from 1 fixture(s)
agora-backend | Performing system checks...
agora-backend | 
agora-backend | System check identified no issues (0 silenced).
agora-backend | June 02, 2021 - 14:41:10
agora-backend | Django version 1.11.29, using settings 'agora.settings'
agora-backend | Starting development server at http://0.0.0.0:80/
agora-backend | Quit the server with CONTROL-C.
agora-backend | [02/Jun/2021 14:41:47] "GET / HTTP/1.1" 302 0
agora-backend | [02/Jun/2021 14:41:47] "GET /ui/ HTTP/1.1" 200 3840
agora-backend | [02/Jun/2021 14:41:48] "GET /ui/assets/vendor.css HTTP/1.1" 200 49164
agora-backend | Not Found: /ui/assets/theme.css
agora-backend | [02/Jun/2021 14:41:48] "GET /ui/assets/theme.css HTTP/1.1" 404 1771
agora-backend | [02/Jun/2021 14:41:48] "GET /ui/assets/agora-admin.css HTTP/1.1" 200 410659
agora-backend | [02/Jun/2021 14:41:48] "GET /ui/assets/agora-admin.js HTTP/1.1" 200 1419322
agora-backend | [02/Jun/2021 14:41:48] "GET /ui/assets/vendor.js HTTP/1.1" 200 5448586
agora-backend | Not Found: /ui/assets/theme.css
agora-backend | [02/Jun/2021 14:41:49] "GET /ui/assets/theme.css HTTP/1.1" 404 1771
agora-backend | [02/Jun/2021 14:41:50] "GET /ui/assets/favicon.ico HTTP/1.1" 200 15406
agora-backend | [02/Jun/2021 14:41:50] "GET /api/v2/config.json HTTP/1.1" 200 20491
agora-backend | [02/Jun/2021 14:41:51] "GET /api/v2/auth/me/ HTTP/1.1" 401 54
agora-backend | [02/Jun/2021 14:41:51] "GET /ui/assets/logo.png HTTP/1.1" 200 2292
agora-backend | [02/Jun/2021 14:41:58] "POST /api/v2/auth/login/ HTTP/1.1" 200 57
agora-backend | [02/Jun/2021 14:41:58] "GET /api/v2/auth/me/ HTTP/1.1" 200 128
agora-backend | [02/Jun/2021 14:41:58] "GET /api/v2/resources/?limit=10&offset=0 HTTP/1.1" 200 3199
agora-backend | [02/Jun/2021 14:41:59] "GET /api/v2/providers/f95b8142-5b51-4044-9d9a-e94759c3554c/ HTTP/1.1" 200 3463
```

The log with timestamp [02/Jun/2021 14:41:58] is when I logged in with user: superadmin password:12345
compare it with your logs and provide any info you think is useful

Best regards

**Comment by MilosQL** [comment]
Hmm, it seems that changing the URL in /etc/agora/deployment.conf to the actual one solved the problem (we have a FQDN and Nginx proxy for HTTPS in front of the whole compose setup). I was eventually able to log in and receive a similar log output as @kevangel79. (Please let me know if this solution actually makes any sense.) 
The thing is, I've skipped the manual installation part of the README.md and jumped directly to the Docker section where this step is not mentioned. 

Also, the HEALTHCHECK command in docker-compose.yml seems to have the wrong port number in the URL. Shouldn't it be http://localhost:80/ui/auth/login instead of http://localhost:8000/ui/auth/login? The 8000 results in _unhealthy_ status:

```
# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS                    NAMES
1f4987ac4dbf        agora-sp_frontend   "docker-entrypoint.s…"   2 hours ago         Up 38 minutes                                        agora-frontend
8b0c0e9d2e62        agora-sp_backend    "bash -c 'python man…"   2 hours ago         Up 38 minutes (unhealthy)   127.0.0.1:8000->80/tcp   agora-backend
``` 
Thank you for your patience so far!

**Comment by kevangel79** [comment]
The docker-compose is used only for local dev. If you want a production deployment check the documentation in django project and ember js respectively.

**Comment by MilosQL** [comment]
Ok, understood.
